// CATEGORIAS
export const ENVIRONMENT_CATEGORY = 1;
export const PERSONAL_DEVELOPMENT_CATEGORY = 2;
export const EDUCATION_CATEGORY = 3;
export const WORK_CATEGORY = 4;

export const FINANCIAL_INCLUSION_CATEGORY = 5;
export const SUSTAINABLE_AGRICULTURE_CATEGORY = 6;
export const MARKETS_ACCESS_CATEGORY = 7;
export const CLIMATE_ADAPTATION_CATEGORY = 8;
export const GIVE4FOREST_SUSTAINABILITY_CATEGORY = 9;

export const ALL_CATEGORIES = [
    /*ENVIRONMENT_CATEGORY,
    PERSONAL_DEVELOPMENT_CATEGORY,
    EDUCATION_CATEGORY,
    WORK_CATEGORY,*/
    FINANCIAL_INCLUSION_CATEGORY,
    SUSTAINABLE_AGRICULTURE_CATEGORY,
    MARKETS_ACCESS_CATEGORY,
    CLIMATE_ADAPTATION_CATEGORY,
    GIVE4FOREST_SUSTAINABILITY_CATEGORY
]