
name: Build and deploy dapp - staging

on:
  push:
    branches: [ master ]
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: rsync lab
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: src/index.js
          remote_path: /var/www/html/dapp
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
   
